### ISSUE TITLE
Add support to handle invalid line number

### ISSUE THREAD

**Issue by rows-s** [discrimy/linthell#2]
`flake8-isort` may produce invalid line number. Linthell unable to handle such cases and raises `IndexError`.

To reproduce:
- install `flake8-isort` plugin
- create file with two lines of code
  ```python
  from flake8.utils import stdin_get_value
  print(stdin_get_value())
  ```
 - lint file using `flake8` wrapped by `linthell`
 
---

flake8 produceds: 
```
path/to/file.py:3:1 : I005 isort found an unexpected missing import
```

And linthell fails with traceback:
```python
Traceback (most recent call last):
  File "commands/pre_commit/lint.py", line 82, in lint_cli
    report = lint(digests, output, lint_format)
  File "linthell/commands/lint.py", line 32, in lint
    id_line = get_id_line(path, line, message)
  File "linthell/utils/id_lines.py", line 18, in get_id_line
    code = lines[int(line) - 1]
IndexError: list index out of range
```

---

Used linthell config:
```
[common]
lint_format = (?P<path>[a-zA-Z0-9\._-]+(?:[\\/][a-zA-Z0-9\._-]+)*):(?P<line>\d+):\d+ : (?P<message>[^\n]+)
linter_command = flake8 --toml-config pyproject.toml
```

Used flake8 config:
```toml
[tool.flake8]
exclude = [
    "venv/*", ".venv/*", ".git", "*/migrations/*", "templates/*", "www/*", "*__init__.py", "manage.py", "settings.py",
]
max-line-length = 120
format = "%(path)s:%(row)d:%(col)d : %(code)s %(text)s"
pytest-fixture-no-parentheses = true
pytest-mark-no-parentheses = true
ignore = [
    "PT009",  # use a regular assert instead of unittest-style '{assertion}'
    "S101",  # Use of assert detected
    "W503",  # line break before binary operator
    "A003",  # class attribute "attr_name" is shadowing a python builtin
]
```

Used isort config:
```toml
[tool.isort]
line_length = 120
include_trailing_comma = true
multi_line_output = 3 
```
